PROGRAM CARPET(INPUT, OUTPUT);

CONST
   WIDTH = 15;
   LENGTH = 12;
   PRICE = 17;

VAR
   AREAINFEET, AREAINYARDS, COST: INTEGER;

BEGIN
   AREAINFEET := WIDTH * LENGTH;
   AREAINYARDS := AREAINFEET DIV 9;
   COST := PRICE * AREAINYARDS;
   WRITELN(' COST IS ',COST)
END.
